### ISSUE TITLE
Correct folder structure and naming

### ISSUE THREAD

**Issue by Planutim** [kk-digital/image-tagging-tools#18]
- There should be two folders

  1. input (with set of tagged images in folders)
  2. output (Where we write the data)
      * it should be  output/input-XXX.json,  not "pixel-art" or variable set

- Verify the readme.md and document the input structure (what is input) and what is output (where stuff goes)

**Comment by Volpe95** [comment]
@Planutim  shouldn't this be already solved in #19  ?
