### ISSUE TITLE
models' folder

### ISSUE THREAD

**Issue by skittoo** [kk-digital/image-tagging-tools#59]
-- put each model type in own sub-folder

**Comment by haltingstate** [comment]
See: https://github.com/kk-digital/image-tagging-tools/issues/56

**Comment by haltingstate** [comment]
API: LIST_MODELS FUNCTIONS

list models + tags (input is directory)
-- one sub-directory for each model type: ex. ./output/models/ovr/, etc
-- input is ./ouputs/models/
